import os
import shutil
import subprocess
import tempfile
import time
from typing import Dict, List, Tuple, Any, Optional, Callable
import openpyxl
from src.local_ai import translate_and_format_faca, ensure_ollama_running, warmup_ollama_model


def ensure_keynote_running():
    """Ensures Keynote.app process is alive before executing AppleScripts to avoid -600."""
    try:
        chk = subprocess.run(["pgrep", "-x", "Keynote"], capture_output=True, text=True)
        if chk.returncode != 0:
            subprocess.run(["open", "-a", "Keynote"])
            time.sleep(1.5)
    except Exception:
        pass


def _sanitize_for_applescript(text: str) -> str:
    """Escape text safely for AppleScript double-quoted literals."""
    if not text:
        return ""
    text = text.replace("\\", "\\\\")
    text = text.replace('"', '\\"')
    text = text.replace("\r\n", "\r").replace("\n", "\r")
    # Keep printable chars and carriage return
    text = "".join(c for c in text if ord(c) >= 32 or c in "\r\t")
    return text


def _normalize_key(text: str) -> str:
    """Normalize string for robust matching across Excel and Keynote."""
    if not text:
        return ""
    # Collapse multiple whitespaces and lowercase
    return " ".join(str(text).strip().lower().split())


def read_excel_faca(excel_path: str) -> Dict[Tuple[str, str], Dict[str, str]]:
    """
    Reads an Excel file generated by Phase 1 (with Category in column 12 / L and FACA filled in column 13 / M).
    Returns mapping of: (normalized_station, normalized_issue) -> {"category": ..., "faca": ...}
    """
    if not os.path.exists(excel_path):
        raise FileNotFoundError(f"File Excel không tồn tại: {excel_path}")

    wb = openpyxl.load_workbook(excel_path, data_only=True)
    ws = wb.active

    data_map: Dict[Tuple[str, str], Dict[str, str]] = {}
    curr_station = ""

    for r in range(4, ws.max_row + 1):
        st_val = ws.cell(r, 3).value
        if st_val is not None and str(st_val).strip():
            curr_station = str(st_val).strip()

        issue_val = ws.cell(r, 7).value
        category_val = ws.cell(r, 12).value   # Column L — Category
        faca_val = ws.cell(r, 13).value       # Column M — FACA

        if curr_station and issue_val:
            st_norm = _normalize_key(curr_station)
            iss_norm = _normalize_key(str(issue_val))
            category_text = str(category_val).strip() if category_val is not None else ""
            faca_text = str(faca_val).strip() if faca_val is not None else ""
            if category_text.lower() == "none":
                category_text = ""
            if faca_text.lower() == "none":
                faca_text = ""

            if category_text or faca_text:
                data_map[(st_norm, iss_norm)] = {"category": category_text, "faca": faca_text}

    return data_map


def read_keynote_faca_structure(keynote_path: str) -> List[Dict[str, Any]]:
    """
    Reads slide tables from a Keynote presentation via AppleScript.
    Returns list of issue rows with (slide, table, row, station, issue, current_category, current_faca).
    """
    abs_key_path = os.path.abspath(keynote_path)
    if not os.path.exists(abs_key_path):
        raise FileNotFoundError(f"File Keynote không tồn tại: {abs_key_path}")

    script = f'''
    tell application "Keynote"
        set myDoc to open POSIX file "{abs_key_path}"
        set sCount to count of slides of myDoc
        set res to ""
        repeat with s from 1 to sCount
            tell slide s of myDoc
                set stName to ""
                set tCount to count of tables
                set targetTable to 0
                if tCount >= 2 then
                    try
                        set stName to value of cell 1 of row 2 of table 1
                    end try
                    set targetTable to 2
                else if tCount = 1 then
                    set targetTable to 1
                end if
                
                if targetTable > 0 then
                    tell table targetTable
                        set numRows to count of rows
                        repeat with r from 2 to numRows
                            set iss to ""
                            set cat to ""
                            set faca to ""
                            try
                                set iss to value of cell 2 of row r
                            end try
                            try
                                set cat to value of cell 5 of row r
                            end try
                            try
                                set faca to value of cell 6 of row r
                            end try
                            if iss is not "" and iss is not "missing value" then
                                if cat is "missing value" then
                                    set cat to ""
                                end if
                                if faca is "missing value" then
                                    set faca to ""
                                end if
                                set res to res & (s as string) & "\\t" & (targetTable as string) & "\\t" & (r as string) & "\\t" & (stName as string) & "\\t" & (iss as string) & "\\t" & (cat as string) & "\\t" & (faca as string) & linefeed
                            end if
                        end repeat
                    end tell
                end if
            end tell
        end repeat
        close myDoc saving no
        return res
    end tell
    '''
    proc = subprocess.run(["osascript", "-e", script], capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"Lỗi khi đọc file Keynote bằng AppleScript: {proc.stderr}")

    rows: List[Dict[str, Any]] = []
    curr_station = ""
    for line in proc.stdout.strip().split("\n"):
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) >= 7:
            s_idx = int(parts[0])
            t_idx = int(parts[1])
            r_idx = int(parts[2])
            st = parts[3].strip()
            if st:
                curr_station = st
            iss = parts[4].strip()
            cat = parts[5].strip()
            faca = parts[6].strip()
            if cat == "missing value":
                cat = ""
            if faca == "missing value":
                faca = ""
            rows.append({
                "slide": s_idx,
                "table": t_idx,
                "row": r_idx,
                "station": curr_station,
                "issue": iss,
                "current_category": cat,
                "current_faca": faca
            })

    return rows


def calculate_faca_updates(
    keynote_rows: List[Dict[str, Any]],
    excel_data_map: Dict[Tuple[str, str], Dict[str, str]],
    mode: str = "excel_priority"
) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """
    Calculates cell updates for both Category (Keynote col 5) and FACA (Keynote col 6)
    based on the selected priority mode:
    - 'keynote_priority': Keep Keynote if present, fill from Excel if Keynote is empty.
    - 'excel_priority': Overwrite with Excel if present, keep Keynote if Excel is empty.
    - 'merge_both': Combine both with newline, don't duplicate if identical.
    """
    updates = []
    matched_count = 0
    updated_count = 0

    for item in keynote_rows:
        st_norm = _normalize_key(item["station"])
        iss_norm = _normalize_key(item["issue"])
        key = (st_norm, iss_norm)

        excel_entry = excel_data_map.get(key, {})
        excel_category = excel_entry.get("category", "").strip()
        excel_faca = excel_entry.get("faca", "").strip()
        kn_category = item.get("current_category", "").strip()
        kn_faca = item.get("current_faca", "").strip()

        if excel_category or excel_faca:
            matched_count += 1

        def _resolve(kn_val: str, xl_val: str) -> str:
            if mode == "keynote_priority":
                return kn_val if kn_val else xl_val
            elif mode == "excel_priority":
                return xl_val if xl_val else kn_val
            elif mode == "merge_both":
                if kn_val and xl_val:
                    if kn_val.lower() == xl_val.lower():
                        return kn_val
                    return f"[Keynote]: {kn_val}\n[Excel]: {xl_val}"
                return kn_val or xl_val
            return kn_val

        new_category = _resolve(kn_category, excel_category)
        new_faca = _resolve(kn_faca, excel_faca)

        changed = (new_category != kn_category) or (new_faca != kn_faca)
        if changed:
            updates.append({
                "slide": item["slide"],
                "table": item["table"],
                "row": item["row"],
                "station": item["station"],
                "issue": item["issue"],
                "old_category": kn_category,
                "new_category": new_category,
                "old_faca": kn_faca,
                "new_faca": new_faca
            })
            updated_count += 1

    stats = {
        "total_scanned": len(keynote_rows),
        "matched_with_excel": matched_count,
        "updated_cells": updated_count
    }
    return updates, stats


def apply_keynote_faca_updates(
    keynote_path: str,
    output_path: str,
    updates: List[Dict[str, Any]],
    log_cb: Optional[Callable[[str], None]] = None
) -> str:
    """
    Applies calculated Category + FACA updates to the output Keynote presentation.
    Category → Keynote Table col 5. FACA → Keynote Table col 6.
    """
    abs_src = os.path.abspath(keynote_path)
    abs_out = os.path.abspath(output_path)

    # 1. Prepare target copy if writing to a new file
    if abs_src != abs_out:
        if log_cb:
            log_cb(f"📋 Tạo bản sao file Keynote mới: {os.path.basename(abs_out)}")
        if os.path.exists(abs_out):
            if os.path.isdir(abs_out):
                shutil.rmtree(abs_out)
            else:
                os.remove(abs_out)

        if os.path.isdir(abs_src):
            shutil.copytree(abs_src, abs_out)
        else:
            shutil.copy2(abs_src, abs_out)

    if not updates:
        if log_cb:
            log_cb("ℹ️ Không có thay đổi nào cần ghi vào Keynote (dữ liệu đã đồng bộ hoặc để trống).")
        return abs_out

    if log_cb:
        log_cb(f"✍️ Đang ghi {len(updates)} mục Category + FACA vào các slide Keynote...")

    ensure_keynote_running()

    # 2. Build AppleScript batch update — writes col 5 (Category) and col 6 (FACA)
    as_lines = [
        'use AppleScript version "2.4"',
        'tell application id "com.apple.Keynote"',
        '    activate',
        '    delay 0.5',
        f'    set myDoc to open POSIX file "{abs_out}"',
        '    delay 0.5',
        '    tell myDoc'
    ]

    for item in updates:
        s_idx = item["slide"]
        t_idx = item["table"]
        r_idx = item["row"]
        new_cat = _sanitize_for_applescript(item.get("new_category", ""))
        new_faca = _sanitize_for_applescript(item.get("new_faca", ""))
        # Write Category to col 5 only when there's a value
        if new_cat:
            as_lines.append(f'        set value of cell 5 of row {r_idx} of table {t_idx} of slide {s_idx} to "{new_cat}"')
        # Always write FACA to col 6 (even empty string clears the cell)
        as_lines.append(f'        set value of cell 6 of row {r_idx} of table {t_idx} of slide {s_idx} to "{new_faca}"')

    as_lines.extend([
        '    end tell',
        '    delay 0.5',
        '    save myDoc',
        '    delay 0.5',
        '    close myDoc saving yes',
        '    return "DONE"',
        'end tell'
    ])

    batch_script = "\n".join(as_lines)

    for attempt in range(2):
        ensure_keynote_running()
        with tempfile.NamedTemporaryFile("w", suffix=".applescript", delete=False) as f:
            f.write(batch_script)
            tmp_script_path = f.name

        try:
            proc = subprocess.run(["osascript", tmp_script_path], capture_output=True, text=True)
        finally:
            if os.path.exists(tmp_script_path):
                os.remove(tmp_script_path)

        if proc.returncode == 0:
            break
        elif attempt == 0 and ("-600" in proc.stderr or "Application isn’t running" in proc.stderr or "Application isn't running" in proc.stderr):
            if log_cb:
                log_cb("⚠️ Keynote cần khởi động lại (-600), đang kích hoạt lại...")
            time.sleep(1.5)
            continue
        else:
            raise RuntimeError(f"Lỗi khi lưu vào Keynote bằng AppleScript: {proc.stderr}")

    if log_cb:
        log_cb(f"✅ Đã cập nhật thành công {len(updates)} mục Category + FACA vào Keynote!")

    return abs_out


def run_phase2_faca_sync(
    excel_path: str,
    keynote_path: str,
    output_dir: str,
    mode: str = "excel_priority",
    save_as_new: bool = True,
    project_name: Optional[str] = None,
    create_english_copy: bool = False,
    log_cb: Optional[Callable[[str], None]] = None
) -> Dict[str, Any]:
    """
    Executes the entire Phase 2 workflow:
    1. Read Excel Category + FACA (cols L & M)
    2. Read Keynote Category + FACA structure (cols 5 & 6)
    3. Calculate diffs based on strategy
    4. Save to new or overwrite Keynote file
    5. Optionally generate an English translated Keynote copy (*_FACA_English.key)
    """
    if log_cb:
        log_cb("🚀 Bắt đầu Phase 2: Đồng bộ Category + FACA từ Excel sang Keynote...")
        log_cb(f"📂 File Excel nguồn: {os.path.basename(excel_path)}")
        log_cb(f"📊 File Keynote đích: {os.path.basename(keynote_path)}")
        log_cb(f"⚙️ Chế độ hợp nhất: {mode}")

    # 1. Parse Excel
    if log_cb:
        log_cb("🔍 Đang đọc dữ liệu Category + FACA từ file Excel...")
    excel_data_map = read_excel_faca(excel_path)
    if log_cb:
        log_cb(f"   ➔ Đã đọc {len(excel_data_map)} mục có Category/FACA từ Excel.")

    # 2. Parse Keynote
    if log_cb:
        log_cb("🔍 Đang quét cấu trúc bảng và trạm trong file Keynote...")
    keynote_rows = read_keynote_faca_structure(keynote_path)
    if log_cb:
        log_cb(f"   ➔ Đã tìm thấy {len(keynote_rows)} dòng lỗi trên các slide Keynote.")

    # 3. Calculate updates
    updates, stats = calculate_faca_updates(keynote_rows, excel_data_map, mode=mode)
    if log_cb:
        log_cb(f"   ➔ Khớp {stats['matched_with_excel']}/{len(keynote_rows)} mục giữa 2 file.")
        log_cb(f"   ➔ Cần cập nhật: {stats['updated_cells']} dòng (Category + FACA).")

    # 4. Determine output file path
    if project_name and project_name.strip():
        base_name = project_name.strip()
    else:
        base_name = os.path.splitext(os.path.basename(keynote_path))[0]

    os.makedirs(output_dir, exist_ok=True)
    if save_as_new:
        out_key_path = os.path.join(output_dir, f"{base_name}_FACA_Updated.key")
    else:
        out_key_path = os.path.abspath(keynote_path)

    # 5. Apply updates
    final_path = apply_keynote_faca_updates(keynote_path, out_key_path, updates, log_cb=log_cb)

    # 6. Optionally create English converted copy
    english_output_path = None
    if create_english_copy:
        if log_cb:
            log_cb("🌐 Bắt đầu tạo thêm bản sao Keynote dịch FACA sang Tiếng Anh...")
        ollama_ok = ensure_ollama_running(log_cb=log_cb)
        if not ollama_ok:
            if log_cb:
                log_cb("⚠️ CẢNH BÁO: Không thể khởi chạy AI server offline. Vui lòng mở lại qua Mo_App_Lan_Dau.command để cấp đủ quyền.")
        else:
            warmup_ollama_model(log_cb=log_cb)

        out_en_path = os.path.join(output_dir, f"{base_name}_FACA_English.key")

        # Map every cell to its post-sync resolved category & faca
        final_cell_map = {}
        for kr in keynote_rows:
            cell_key = (kr["slide"], kr["table"], kr["row"])
            final_cell_map[cell_key] = {
                "slide": kr["slide"],
                "table": kr["table"],
                "row": kr["row"],
                "station": kr["station"],
                "issue": kr["issue"],
                "category": kr.get("current_category", ""),
                "faca": kr.get("current_faca", "")
            }

        # Override with updates that were applied
        for u in updates:
            cell_key = (u["slide"], u["table"], u["row"])
            if cell_key in final_cell_map:
                final_cell_map[cell_key]["category"] = u.get("new_category", "")
                final_cell_map[cell_key]["faca"] = u.get("new_faca", "")

        en_updates = []
        translated_count = 0
        total_to_translate = sum(1 for c in final_cell_map.values() if c.get("faca", "").strip())

        for cell_key, cell_info in final_cell_map.items():
            faca = cell_info["faca"]
            cat = cell_info["category"]
            st = cell_info["station"]
            if faca:
                if log_cb:
                    log_cb(f"   🤖 Dịch FACA [{st}]: {faca[:35]}...")
                en_faca = translate_and_format_faca(faca, category=cat, station=st, log_cb=log_cb)
                if en_faca and en_faca.strip() != faca.strip():
                    translated_count += 1
            else:
                en_faca = ""

            en_updates.append({
                "slide": cell_info["slide"],
                "table": cell_info["table"],
                "row": cell_info["row"],
                "station": st,
                "issue": cell_info["issue"],
                "new_category": cat,
                "new_faca": en_faca
            })

        if log_cb:
            log_cb(f"   ➔ Đã dịch xong {translated_count}/{total_to_translate} mục FACA sang Tiếng Anh.")

        apply_keynote_faca_updates(keynote_path, out_en_path, en_updates, log_cb=log_cb)
        english_output_path = out_en_path
        if log_cb:
            log_cb(f"✅ Đã tạo file Keynote Tiếng Anh: {os.path.basename(out_en_path)}")

    result = {
        "success": True,
        "output_path": final_path,
        "english_output_path": english_output_path,
        "total_scanned": stats["total_scanned"],
        "matched_with_excel": stats["matched_with_excel"],
        "updated_cells": stats["updated_cells"],
        "mode": mode
    }

    if log_cb:
        log_cb(f"🎉 Hoàn tất Phase 2! File kết quả: {os.path.basename(final_path)}")

    return result
